// Редактируемый контент портфолио.
// Добавляй новые языки в supportedLangs и translations с теми же ключами, что у en/es/ru.
window.portfolioContent = {
    defaultLang: "en",
    supportedLangs: ["en", "es", "ru"],
    contacts: [
        {
            label: "Email",
            href: "mailto:egorpavlov024@gmail.com",
            iconClass: "fas fa-envelope",
        },
        {
            label: "Telegram",
            href: "https://t.me/Slyfoxy",
            iconClass: "fab fa-telegram-plane",
        },
        {
            label: "LinkedIn",
            href: "https://www.linkedin.com/in/egor-pavlov-824b02281/",
            iconClass: "fab fa-linkedin",
        },
        {
            label: "GitHub",
            href: "https://github.com/SlyFox-maker/SlyFox-maker",
            iconClass: "fab fa-github",
        },
    ],
    translations: {
        en: {
            title: "Full Stack Engineer",
            hero_focus: "Backend · Desktop Development · Integrations",
            work_mode: "Remote",
            location: "Based in Mexico",
            availability: "Open to opportunities",
            cta_projects: "View projects",
            cta_contact: "Contact me",
            intro: "I’m Egor Pavlov, a Full Stack engineer. I build web and desktop applications, backend systems, CRM integrations, and automation tools. I work across the full project lifecycle — from architecture and business logic to interfaces, Docker infrastructure, and deployment.",
            skills: "Key Skills",
            skills_list: ["Fullstack development (frontend + backend)", "Languages: C++, C#, Python, Java, JavaScript, PHP", "Frameworks & libraries: Django, Vue.js, Node.js, Qt, .NET", "Desktop apps: Qt, WinForms, JavaFX, .NET", "DevOps: Linux, Git, Docker, CI/CD, automation", "CRM/API integrations (Bitrix24, amoCRM, custom webhooks)", "Databases: PostgreSQL, MySQL, SQLite, MongoDB", "Working with REST APIs, JSON, XML, WebSocket"],
            skill_groups: [
                { title: "Backend", icon: "fas fa-server", items: ["Python", "Django", "Node.js", "PHP", "REST API", "WebSocket"] },
                { title: "Frontend & Full Stack", icon: "fas fa-code", items: ["JavaScript", "Vue.js", "HTML/CSS", "Bootstrap", "jQuery"] },
                { title: "Desktop & Systems", icon: "fas fa-desktop", items: ["C++", "C#", "Java", "Qt", ".NET", "WinForms", "JavaFX"] },
                { title: "DevOps & Integrations", icon: "fas fa-gears", items: ["Docker", "Linux", "CI/CD", "Bitrix24", "amoCRM", "PostgreSQL", "MySQL"] },
            ],
            projects: "Projects",
            projects_commercial: "Commercial Projects",
            projects_pet: "Pet Projects",
            project_role_label: "Role: ",
            project_result_label: "Result: ",
            image_loading: "Loading image...",
            nav_label: "Portfolio journey",
            nav_prompt: "Explore",
            nav_overview: "Overview",
            nav_skills: "Skills",
            nav_projects: "Projects",
            nav_education: "Education",
            nav_certificates: "Certificates",
            nav_contact: "Contact",
            nav_start: "Start exploring",
            certs_show_all: "Show all certificates",
            certs_show_less: "Show fewer certificates",
            certs_key: "Key certificates",
            certs_additional: "Additional certificates",
            degree_summary: "Bachelor’s graduate in Software and Network Engineering from UVM. Currently pursuing a Master’s degree in Engineering with a specialization in Artificial Intelligence.",
            education_more: "Education details",
            education_less: "Hide details",

            project_list: [
                {
                    name: "Online Booking and Access Control (SCUD) Integration Platform",
                    type: "commercial",
                    areas: ["Product Development", "CRM Integration", "Access Control", "Payments", "Infrastructure"],
                    role: "Lead developer: backend, frontend, Docker deployment, CRM and access-control integration.",
                    impact: "Unified booking, payments, Bitrix24 synchronization, and room access management in one production system.",
                    stack: ["Django", "Docker", "Bitrix24", "PHP", "WebSocket"],
                    file: ["./projects/24reson/1.png", "./projects/24reson/2.png", "./projects/24reson/3.png"],
                    desc: "Commercial project for a company combining online meeting room and tariff booking with integration into the access control system (SCUD) and Bitrix24 CRM. I implemented the backend in Django using Docker, ensuring convenient deployment and environment management. The system includes user registration, personal dashboard, booking calendar, and data synchronization with Bitrix24. Configured automatic creation of client, deal, and product cards in the CRM, as well as access management to premises via SCUD. Developed a SCUD server in pure PHP with command exchange via WebSocket and logging of all access events. The system supports bidirectional synchronization, payment processing, and dynamic management of branches, tariffs, and rooms. Led a team of 3 people, handling most of the backend and frontend work.",
                    sections: [
                        {
                            title: "What it is",
                            text: "A commercial system for booking meeting rooms and managing tariffs, payments, CRM records, and physical access to rooms. The idea was to make the online booking flow, Bitrix24 CRM, and the SCUD access-control layer work together instead of being handled as separate processes.",
                        },
                        {
                            title: "What I did",
                            text: "I built most of the product end-to-end: Django backend, frontend flows, Docker deployment, authentication, personal dashboards, booking calendar, and management tools for branches, tariffs, and rooms. I set up real-time synchronization with Bitrix24 and automated the creation of clients, deals, products, and booking-related CRM data. I also connected payments and user roles to access permissions, then built a separate SCUD service in pure PHP with WebSocket command exchange and real-time logs for door/access events.",
                        },
                        {
                            title: "Impact",
                            text: "The system removed a lot of manual coordination between bookings, CRM, payments, and room access. Staff can manage branches, tariffs, rooms, users, access events, and CRM data from one place, while the platform keeps the booking system, Bitrix24, payment logic, and access-control service synchronized.",
                        },
                    ],
                },
                {
                    name: "PWA Application for Client Notifications and Legal Support",
                    type: "commercial",
                    areas: ["Client Portal", "Backend API", "CRM Integration", "Notifications"],
                    role: "Backend owner: API architecture, Docker setup, Bitrix24 integration, Telegram bot connection.",
                    impact: "Gave clients a personal dashboard for debts, payments, notifications, and direct legal support.",
                    stack: ["Flask", "Docker", "Vue", "Bitrix24", "Telegram API"],
                    file: ["./projects/pwa_site/1.png"],
                    desc: "Commercial Progressive Web App project for client interaction with the company’s legal department. Developed an API server in Flask (Python) using Docker as the central component to integrate the app with Bitrix24 CRM and a Telegram bot. Clients can view debts, receive notifications, pay for services, and contact lawyers directly through their personal dashboard. Each client has an individual case with status tracking. Frontend was developed in Vue.js (Vite); I personally handled backend integration and business logic. Worked in a team of 3 people, responsible for the entire server side, Docker setup, and backend integration with the layout made by other developers.",
                    sections: [
                        {
                            title: "What it is",
                            text: "A commercial PWA for communication between clients and a legal services department. Clients use a personal dashboard to follow their legal case, see payment-related information, receive updates, and contact lawyers directly.",
                        },
                        {
                            title: "What I did",
                            text: "I designed and implemented the Flask backend: REST API structure, business logic, service-to-service data flow, Bitrix24 CRM integration, and a Telegram notification bot. I containerized the backend with Docker and connected it to a Vue.js (Vite) frontend built by the team. My part included wiring screens to API endpoints, case status logic, payment data, notifications, and client communication flows. I worked in a 3-person team and owned the backend architecture, API design, Docker setup, and deployment pipeline.",
                        },
                        {
                            title: "Impact",
                            text: "Clients got a clearer way to track their case, receive updates, manage payments, and communicate with the legal team. For internal staff, the project reduced manual status updates and made CRM synchronization, notifications, and case tracking part of one workflow.",
                        },
                    ],
                },
                {
                    name: "Story-driven Minecraft Mod with Unique Gameplay Mechanics",
                    type: "pet",
                    areas: ["Game Systems", "NPC Logic", "Storytelling", "Event-driven Mechanics"],
                    role: "Gameplay programmer: event systems, NPC logic, bosses, triggers, and progression mechanics.",
                    impact: "Turned a server into a story-driven adventure with dynamic music, allies, enemies, and multiple endings.",
                    stack: ["Java", "Spigot", "Game Logic", "Events"],
                    file: ["./projects/strangers_in_rosaville/1.png", "./projects/strangers_in_rosaville/2.png", "./projects/strangers_in_rosaville/3.png", "./projects/strangers_in_rosaville/4.png"],
                    desc: "Java Spigot project for Minecraft servers turning the game into a full-fledged adventure with story, secrets, and dynamic events. Developed a background music system that changes depending on location and map triggers. Created friendly NPCs that can talk, follow the player, and assist in progression, as well as enemy NPCs with unique personalities and possible plot twists (an enemy can become an ally). Implemented boss fights, multiple endings, and interactive mechanics, including custom tools and skins. Worked in a team of 2: I handled all programming and coding, while another developer worked on skins, design, and story. I also contributed to content and story creation. The project showcases skills in complex game system development, event management, and integration of various mechanics.",
                    sections: [
                        {
                            title: "What it is",
                            text: "A Java Spigot pet project for a Minecraft server. We wanted to make the server feel more like a small adventure: with story moments, secrets, dynamic events, progression, and custom interactions.",
                        },
                        {
                            title: "What I built",
                            text: "I handled the code and gameplay logic in a 2-person team. I made adaptive music that changes by location and triggers, friendly NPCs with dialogue and companion behavior, enemies with their own personality and possible relationship changes, boss fights, multiple endings, custom tools, skins, and scripted world interactions. I also helped with content and story ideas while my teammate focused more on skins, design, and narrative material.",
                        },
                        {
                            title: "What it shows",
                            text: "It was a fun project, but it had real technical depth. I practiced event-driven gameplay, NPC logic, trigger systems, branching outcomes, and interactive mechanics in Java while turning a regular server into something closer to a small story-driven game.",
                        },
                    ],
                },
                {
                    name: "Personal Cloud Storage (Google Drive Alternative)",
                    type: "pet",
                    areas: ["Full-stack Product", "File Management", "User Quotas", "Admin Tools"],
                    role: "Solo developer: product logic, backend, frontend, admin tools, and Docker environment.",
                    impact: "Built a working private cloud with storage quotas and full file management workflows.",
                    stack: ["Django", "Docker", "Bootstrap", "jQuery"],
                    file: ["./projects/fileExchange/1.png", "./projects/fileExchange/2.png", "./projects/fileExchange/3.png"],
                    desc: "Personal project in Django with Docker, Bootstrap, and jQuery functioning as personal cloud storage with features similar to Google Drive. Implemented allocated storage control for users, display of remaining space in a clear interface, and file management capabilities: move, copy, rename, delete, and view details. Includes an admin system for managing users and storage. The project demonstrates skills in complex web application development, server-side logic handling, frontend-backend integration, and managing large amounts of data. Fully developed by me, including Docker setup and both frontend and backend development.",
                    sections: [
                        {
                            title: "What it is",
                            text: "A personal cloud storage pet project, close in idea to a small Google Drive-style system. I built it to practice user storage limits, file workflows, and admin-side management.",
                        },
                        {
                            title: "What I built",
                            text: "I built the full application myself with Django, Docker, Bootstrap, and jQuery. It includes user storage quotas, remaining-space display, admin tools for users and storage, and file operations such as move, copy, rename, delete, and viewing file details. I handled both backend and frontend, including server-side logic, UI integration, and Docker setup.",
                        },
                        {
                            title: "What it shows",
                            text: "It shows practical full-stack work: user management, storage quotas, file flows, admin features, frontend-backend integration, and working with file-oriented data beyond a simple static website.",
                        },
                    ],
                },
            ],

            certs: "Certificates",
            certs_list: [
                {
                    name: "Web & Mobile Application Developer Diploma",
                    file: "./cert/Carlos/diplomeDev.png",
                    desc: "Issued for completing a comprehensive course in full-cycle web development — including frontend (HTML, CSS, JavaScript, UI/UX) and backend (PHP, Python, databases) — as well as mobile app creation using Progressive Web Apps (PWA) technology.",
                    featured: true,
                },
                {
                    name: "Cisco CCNA 4: CyberOps Associate",
                    file: "./cert/Cisco/CCNA4.png",
                    desc: "Confirms successful completion of the Cisco CyberOps Associate course focused on cybersecurity operations and Security Operations Center (SOC) practices. Covered network monitoring, threat and incident analysis, network protocols, and attack detection techniques. Gained hands-on experience in digital forensics, endpoint protection, network traffic analysis, and the use of tools such as Wireshark, SIEM platforms, and incident response technologies.",
                    featured: true,
                },
                {
                    name: "Cisco CCNA 3: Enterprise Networking, Security and Automation",
                    file: "./cert/Cisco/CCNA3.png",
                    desc: "Confirms successful completion of the third course in the CCNA certification preparation program. Covered enterprise networking technologies, OSPF routing, WAN infrastructure, network security fundamentals, and automation concepts. Gained hands-on experience with securing network devices and traffic, configuring ACLs, VPNs and SSH, as well as modern SDN, virtualization, and network infrastructure automation approaches.",
                    featured: true,
                },
                {
                    name: "Cisco CCNA 2: Switching, Routing, and Wireless Essentials",
                    file: "./cert/Cisco/CCNA2.png",
                    desc: "Certifies the successful completion of the second course in the CCNA certification training program. Covers key switching, routing, and wireless networking technologies. Includes configuration and management of VLANs, inter-VLAN routing, STP and EtherChannel protocols, setup of Cisco routers and switches, as well as fundamentals of LAN/WLAN design and security.",
                    featured: true,
                },

                {
                    name: "Cisco CCNA 1: Introduction to Networks",
                    file: "./cert/Cisco/CCNA1.png",
                    desc: "Certifies successful completion of the first of three courses in the CCNA certification pathway. Covers networking fundamentals including network architecture, OSI model, IPv4/IPv6 addressing, routing, Ethernet protocols, and basic device configuration using Cisco CLI.",
                },
                {
                    name: "Cisco IT Essentials: PC Hardware and Software",
                    file: "./cert/Cisco/IT_Essentials.png",
                    desc: "Certifies successful completion of the Cisco IT Essentials course. Covers fundamentals of PC and mobile device hardware and software: internal components, system assembly, OS and application installation, hardware/software troubleshooting and maintenance, printers and mobile devices, basic networking and security, virtualization and cloud computing.",
                },
                {
                    name: "IBM Data Visualization with Python",
                    file: "./cert/IBM/Data Visualization with Python.png",
                    desc: "Confirms successful completion of the IBM Data Visualization with Python course. Covered data visualization and analysis techniques using Python and libraries such as Matplotlib, Seaborn, Plotly, and Folium. Gained hands-on experience in creating interactive charts, dashboards, maps, diagrams, and visual reports, as well as presenting and interpreting data for Data Science and analytics projects.",
                    featured: true,
                },
                {
                    name: "IBM Python 101 for Data Science",
                    file: "./cert/IBM/Python 101 for Data Science.png",
                    desc: "Confirms successful completion of the IBM Python 101 for Data Science course. Covered Python programming fundamentals, data structures, functions, loops, file handling, and object-oriented programming. Gained hands-on experience with Pandas and NumPy, working in Jupyter Notebook environments, data processing and analysis, as well as basic automation and data preparation techniques for Data Science projects.",
                    featured: true,
                },
                {
                    name: "UCI Project Initiation and Planning",
                    file: "./cert/Coursera/Inicio y planificación de proyectos.png",
                    desc: "Confirms successful completion of the UCI Project Initiation and Planning course by the University of California, Irvine. Covered project management fundamentals, project planning and goal definition, stakeholder management, scope management, and Work Breakdown Structure (WBS) development. Gained practical knowledge in project documentation, risk evaluation, organizational structures, and effective collaboration within project teams.",
                },
                {
                    name: "Microsoft & UCI Project Management Fundamentals",
                    file: "./cert/Coursera/Project Management Fundamentals.png",
                    desc: "Confirms successful completion of the Project Management Fundamentals course by Microsoft. Covered core project management principles, project lifecycle, task and resource planning, risk management, scheduling, and budgeting. Gained practical knowledge in team collaboration, project tracking, documentation, and the use of modern project management tools and methodologies.",
                },
                {
                    name: "OOP Programmer Certificate",
                    file: "./cert/Carlos/programadorOOP.png",
                    desc: "Covers core concepts of object-oriented programming (OOP), such as encapsulation, inheritance, polymorphism, and abstraction, with practical implementation in high-level languages.",
                },
                {
                    name: "Front-end Developer Certificate",
                    file: "./cert/Carlos/devFrontEnd.png",
                    desc: "Awarded for completing a course in frontend development, focusing on HTML5, CSS3, JavaScript, responsive design, cross-browser compatibility, and UI/UX design principles.",
                },
                {
                    name: "Back-end Developer Certificate",
                    file: "./cert/Carlos/devBackEnd.png",
                    desc: "Confirms proficiency in backend development with PHP and Python, database management, REST API integration, web app architecture, and security practices.",
                },
                {
                    name: "Game Developer Certificate",
                    file: "./cert/Carlos/devGame.png",
                    desc: "Covers fundamentals of game development including game design, programming in Unity, as well as basic marketing and monetization strategies in the gaming industry.",
                },
                {
                    name: "Mobile Developer Certificate",
                    file: "./cert/Carlos/devPhone.png",
                    desc: "Certifies knowledge in mobile development using PWA technology — building cross-platform apps with offline access, installation capabilities, and device integration.",
                },
            ],

            degree: "Degree",
            degree_text: "I earned a Bachelor’s Degree in Software and Network Engineering from Universidad del Valle de México (UVM), where I received both theoretical and hands-on training in modern software development, systems engineering, and IT infrastructure.\n\nDuring my studies, I combined academic training with freelance and professional industry experience, which allowed me to apply technical knowledge in real-world environments and develop a practical, well-rounded engineering skill set.\n\nCurrently pursuing a Master’s degree in Engineering with a specialization in Artificial Intelligence at UVM. The program focuses on machine learning, intelligent systems, data-driven solutions, and modern software engineering practices. I am developing advanced technical skills and applying AI methods to real-world problems.",
            degree_tags_title: "Key areas of study",
            degree_tags: ["C", "C++", "C#", "Java", "Python", "SQL", "Relational databases", "Android", "Mobile development", "Network infrastructure", "Operating systems", "Automation", "Computer architecture", "Software engineering", "System analysis", "Modeling", "Cybersecurity", "Data communication protocols"],
            education_programs: [
                {
                    id: "uvm-bachelor",
                    label: "UVM Bachelor’s Degree",
                    school: "Universidad del Valle de México",
                    title: "Bachelor’s Degree, Ingeniero en Diseño de Redes y Software",
                    period: "May 2023 - May 2026",
                    status: "Completed",
                    gradeLabel: "Grade",
                    grade: "9.71",
                    start: "2023-05",
                    end: "2026-05",
                    celebration: "University completed. Software and Network Engineering unlocked.",
                    documents: [
                        {
                            name: "Bachelor’s graduation certificate",
                            file: "./cert/uvm/diploma.png",
                            desc: "Graduation certificate issued by Universidad del Valle de México (UVM) on August 5, 2026. It confirms that I successfully completed the Bachelor’s program in Software and Network Design Engineering (Licenciatura en Ingeniería en Diseño de Software y Redes).",
                        },
                        {
                            name: "EGEL final exam certificate",
                            file: "./cert/uvm/Egel.png",
                            desc: "Confirms completion of the EGEL final exam at Universidad del Valle de México (UVM), serving as an additional supporting document for my completed bachelor’s studies.",
                        },
                    ],
                },
                {
                    id: "masters-current",
                    label: "UVM Master’s Degree",
                    school: "Universidad del Valle de México",
                    title: "Master’s Degree in Engineering with a Specialization in Artificial Intelligence",
                    period: "Jun 2026 - Jul 2028",
                    status: "In progress",
                    start: "2026-06",
                    end: "2028-07",
                    celebration: "Master’s degree in Artificial Intelligence in progress. Next academic chapter is online.",
                    documents: [],
                },
            ],
        },

        es: {
            title: "Ingeniero Full Stack",
            hero_focus: "Backend · Desarrollo de escritorio · Integraciones",
            work_mode: "Remoto",
            location: "Residente en México",
            availability: "Abierto a oportunidades",
            cta_projects: "Ver proyectos",
            cta_contact: "Contactarme",
            intro: "Soy Egor Pavlov, ingeniero Full Stack. Desarrollo aplicaciones web y de escritorio, sistemas backend, integraciones CRM y herramientas de automatización. Trabajo en todo el ciclo del proyecto: desde la arquitectura y la lógica de negocio hasta las interfaces, la infraestructura Docker y el despliegue.",
            skills: "Habilidades Clave",
            skills_list: ["Desarrollo fullstack (frontend + backend)", "Lenguajes: C++, C#, Python, Java, JavaScript, PHP", "Frameworks y librerías: Django, Vue.js, Node.js, Qt, .NET", "Aplicaciones de escritorio: Qt, WinForms, JavaFX, .NET", "DevOps: Linux, Git, Docker, CI/CD, automatización", "Integraciones CRM/API (Bitrix24, amoCRM, webhooks personalizados)", "Bases de datos: PostgreSQL, MySQL, SQLite, MongoDB", "Trabajo con REST APIs, JSON, XML, WebSocket"],
            skill_groups: [
                { title: "Backend", icon: "fas fa-server", items: ["Python", "Django", "Node.js", "PHP", "REST API", "WebSocket"] },
                { title: "Frontend y Full Stack", icon: "fas fa-code", items: ["JavaScript", "Vue.js", "HTML/CSS", "Bootstrap", "jQuery"] },
                { title: "Escritorio y sistemas", icon: "fas fa-desktop", items: ["C++", "C#", "Java", "Qt", ".NET", "WinForms", "JavaFX"] },
                { title: "DevOps e integraciones", icon: "fas fa-gears", items: ["Docker", "Linux", "CI/CD", "Bitrix24", "amoCRM", "PostgreSQL", "MySQL"] },
            ],
            projects: "Proyectos",
            projects_commercial: "Proyectos comerciales",
            projects_pet: "Proyectos personales",
            project_role_label: "Rol: ",
            project_result_label: "Resultado: ",
            image_loading: "Cargando imagen...",
            nav_label: "Recorrido del portafolio",
            nav_prompt: "Explorar",
            nav_overview: "Resumen",
            nav_skills: "Habilidades",
            nav_projects: "Proyectos",
            nav_education: "Educación",
            nav_certificates: "Certificados",
            nav_contact: "Contacto",
            nav_start: "Comenzar recorrido",
            certs_show_all: "Mostrar todos los certificados",
            certs_show_less: "Mostrar menos certificados",
            certs_key: "Certificados principales",
            certs_additional: "Certificados adicionales",
            degree_summary: "Graduado de la Licenciatura en Ingeniería en Diseño de Software y Redes en UVM. Actualmente curso una Maestría en Ingeniería con especialización en Inteligencia Artificial.",
            education_more: "Detalles de formación",
            education_less: "Ocultar detalles",
            project_list: [
                {
                    name: "Plataforma de integración de reservas en línea y control de acceso (SCUD)",
                    type: "commercial",
                    areas: ["Desarrollo de producto", "Integración CRM", "Control de acceso", "Pagos", "Infraestructura"],
                    role: "Desarrollador líder: backend, frontend, despliegue Docker, integración CRM y control de acceso.",
                    impact: "Unifiqué reservas, pagos, sincronización con Bitrix24 y gestión de acceso a salas en un sistema productivo.",
                    stack: ["Django", "Docker", "Bitrix24", "PHP", "WebSocket"],
                    file: ["./projects/24reson/1.png", "./projects/24reson/2.png", "./projects/24reson/3.png"],
                    desc: "Proyecto comercial para una empresa que combina la reserva en línea de salas de reuniones y tarifas con integración en el sistema de control de acceso (SCUD) y CRM Bitrix24. Desarrollé el backend en Django utilizando Docker, garantizando un despliegue conveniente y gestión del entorno. El sistema incluye registro de usuarios, panel personal, calendario de reservas y sincronización de datos con Bitrix24. Configuré la creación automática de tarjetas de clientes, negocios y productos en el CRM, así como la gestión de acceso a las instalaciones a través del SCUD. Desarrollé un servidor SCUD en PHP puro con intercambio de comandos vía WebSocket y registro de todos los eventos de acceso. El sistema soporta sincronización bidireccional, procesamiento de pagos y gestión dinámica de sucursales, tarifas y salas. Dirigí un equipo de 3 personas, realizando la mayor parte del backend y frontend.",
                    sections: [
                        {
                            title: "Qué es",
                            text: "Un sistema comercial para reservar salas, gestionar tarifas, pagos, registros CRM y acceso físico a las salas. La idea fue hacer que el flujo de reservas, Bitrix24 CRM y la capa de control de acceso SCUD trabajaran juntos en lugar de mantenerse como procesos separados.",
                        },
                        {
                            title: "Qué hice",
                            text: "Desarrollé la mayor parte del producto de extremo a extremo: backend en Django, flujos frontend, despliegue con Docker, autenticación, paneles personales, calendario de reservas y herramientas para gestionar sucursales, tarifas y salas. Configuré sincronización en tiempo real con Bitrix24 y automaticé la creación de clientes, negocios, productos y datos relacionados con reservas. También conecté pagos y roles de usuario con permisos de acceso físico, y desarrollé un servicio SCUD en PHP puro con comandos por WebSocket y registros de eventos de acceso en tiempo real.",
                        },
                        {
                            title: "Impacto",
                            text: "El sistema redujo mucha coordinación manual entre reservas, CRM, pagos y acceso a salas. El equipo puede gestionar sucursales, tarifas, salas, usuarios, eventos de acceso y datos CRM desde un solo lugar, mientras la plataforma mantiene sincronizados el sistema de reservas, Bitrix24, pagos y control de acceso.",
                        },
                    ],
                },
                {
                    name: "Aplicación PWA para notificaciones a clientes y soporte legal",
                    type: "commercial",
                    areas: ["Portal de clientes", "API backend", "Integración CRM", "Notificaciones"],
                    role: "Responsable backend: arquitectura API, Docker, integración con Bitrix24 y conexión con Telegram bot.",
                    impact: "Creé un panel para clientes con deudas, pagos, notificaciones y contacto directo con soporte legal.",
                    stack: ["Flask", "Docker", "Vue", "Bitrix24", "Telegram API"],
                    file: ["./projects/pwa_site/1.png"],
                    desc: "Proyecto comercial en formato Progressive Web App para la interacción de clientes con el departamento legal de la empresa. Desarrollé un servidor API en Flask (Python) utilizando Docker como pieza central para integrar la aplicación con el CRM Bitrix24 y un bot de Telegram. Los clientes, a través de su panel personal, pueden consultar deudas, recibir notificaciones, pagar servicios y comunicarse directamente con los abogados. Para cada cliente se lleva un caso individual con seguimiento de estado. El frontend fue desarrollado en Vue.js (Vite); me encargué personalmente de la integración con el backend y la lógica de negocio. Trabajé en un equipo de 3 personas, siendo responsable de toda la parte del servidor, configuración de Docker y conexión del backend con el maquetado hecho por otros desarrolladores.",
                    sections: [
                        {
                            title: "Qué es",
                            text: "Una PWA comercial para la comunicación entre clientes y un departamento de servicios legales. Los clientes usan un panel personal para seguir su caso, ver información relacionada con pagos, recibir actualizaciones y contactar directamente con abogados.",
                        },
                        {
                            title: "Qué hice",
                            text: "Diseñé e implementé el backend en Flask: estructura REST API, lógica de negocio, intercambio de datos entre servicios, integración con Bitrix24 CRM y un bot de Telegram para notificaciones. Empaqueté el backend con Docker y lo conecté con un frontend Vue.js (Vite) desarrollado por el equipo. Mi parte incluyó conectar pantallas con endpoints, estados de casos, datos de pagos, notificaciones y flujos de comunicación con clientes. Trabajé en un equipo de 3 personas y fui responsable de la arquitectura backend, diseño de API, configuración Docker y pipeline de despliegue.",
                        },
                        {
                            title: "Impacto",
                            text: "Los clientes obtuvieron una forma más clara de seguir su caso, recibir actualizaciones, gestionar pagos y comunicarse con el equipo legal. Para el equipo interno, el proyecto redujo actualizaciones manuales y juntó CRM, notificaciones y seguimiento de casos en un mismo flujo de trabajo.",
                        },
                    ],
                },
                {
                    name: "Mod de Minecraft con historia y mecánica de juego única",
                    type: "pet",
                    areas: ["Sistemas de juego", "Lógica de NPC", "Narrativa", "Mecánicas por eventos"],
                    role: "Programador gameplay: eventos, lógica de NPC, jefes, triggers y progresión.",
                    impact: "Convertí un servidor en una aventura con música dinámica, aliados, enemigos y múltiples finales.",
                    stack: ["Java", "Spigot", "Game Logic", "Events"],
                    file: ["./projects/strangers_in_rosaville/1.png", "./projects/strangers_in_rosaville/2.png", "./projects/strangers_in_rosaville/3.png", "./projects/strangers_in_rosaville/4.png"],
                    desc: "Proyecto en Java Spigot para servidores de Minecraft que convierte el juego en una aventura completa con historia, secretos y eventos dinámicos. Desarrollé un sistema de música de fondo que cambia según la ubicación y los activadores en el mapa. Se crearon NPC amistosos que pueden dialogar, seguir al jugador y ayudar en la aventura, así como NPC enemigos con personalidad única y posibles giros de trama (el enemigo puede convertirse en aliado). Implementé batallas contra jefes, varios finales y mecánicas interactivas, incluyendo herramientas y skins personalizados. El trabajo se realizó en un equipo de 2 personas: me encargué completamente de la programación y código, mientras que otro desarrollador trabajó en skins, diseño e historia. También participé en la creación de contenido y guion. El proyecto demuestra habilidades en desarrollo de sistemas de juego complejos, gestión de eventos e integración de diversas mecánicas.",
                    sections: [
                        {
                            title: "Qué es",
                            text: "Un pet project en Java Spigot para un servidor de Minecraft. Queríamos que el servidor se sintiera más como una pequeña aventura: con historia, secretos, eventos dinámicos, progresión e interacciones personalizadas.",
                        },
                        {
                            title: "Qué construí",
                            text: "Me encargué del código y de la lógica gameplay en un equipo de 2 personas. Hice música adaptativa por ubicación y triggers, NPC amistosos con diálogo y comportamiento de acompañante, enemigos con personalidad y posibles cambios de relación, jefes, varios finales, herramientas, skins e interacciones del mundo por eventos. También aporté ideas de contenido e historia, mientras mi compañero se enfocó más en skins, diseño y material narrativo.",
                        },
                        {
                            title: "Qué demuestra",
                            text: "Fue un proyecto divertido, pero con bastante parte técnica. Practiqué gameplay por eventos, lógica de NPC, sistemas de triggers, resultados ramificados y mecánicas interactivas en Java mientras convertíamos un servidor normal en algo más cercano a una pequeña aventura narrativa.",
                        },
                    ],
                },
                {
                    name: "Almacenamiento en la nube personal (similar a Google Drive)",
                    type: "pet",
                    areas: ["Producto full-stack", "Gestión de archivos", "Cuotas de usuario", "Administración"],
                    role: "Desarrollador solo: lógica de producto, backend, frontend, administración y entorno Docker.",
                    impact: "Construí una nube privada funcional con cuotas de almacenamiento y gestión completa de archivos.",
                    stack: ["Django", "Docker", "Bootstrap", "jQuery"],
                    file: ["./projects/fileExchange/1.png", "./projects/fileExchange/2.png", "./projects/fileExchange/3.png"],
                    desc: "Proyecto personal en Django con Docker, Bootstrap y jQuery que funciona como almacenamiento en la nube personal con funcionalidades similares a Google Drive. Implementé control de espacio asignado para usuarios, visualización del espacio restante en una interfaz clara, así como gestión de archivos: mover, copiar, renombrar, eliminar y ver información. Incluye sistema de administración para gestión de usuarios y almacenamiento. El proyecto demuestra habilidades en desarrollo de aplicaciones web complejas, trabajo con lógica de servidor, integración del frontend con el backend y manejo de grandes volúmenes de datos. Fue desarrollado completamente por mí, incluyendo configuración de Docker y desarrollo frontend y backend.",
                    sections: [
                        {
                            title: "Qué es",
                            text: "Un pet project de almacenamiento en la nube personal, parecido en idea a un pequeño Google Drive. Lo hice para practicar límites de almacenamiento por usuario, flujos de archivos y administración.",
                        },
                        {
                            title: "Qué construí",
                            text: "Construí toda la aplicación con Django, Docker, Bootstrap y jQuery. Incluye cuotas de almacenamiento por usuario, visualización del espacio restante, herramientas de administración para usuarios y almacenamiento, y operaciones de archivos como mover, copiar, renombrar, eliminar y ver detalles. Me encargué tanto del backend como del frontend, incluyendo lógica del servidor, integración UI y configuración Docker.",
                        },
                        {
                            title: "Qué demuestra",
                            text: "Muestra trabajo fullstack práctico: gestión de usuarios, cuotas, flujos de archivos, administración, integración frontend-backend y manejo de datos orientados a archivos, más allá de una página estática simple.",
                        },
                    ],
                },
            ],
            certs: "Certificados",
            certs_list: [
                {
                    name: "Diploma de Desarrollador de Sitios Web y Aplicaciones Móviles",
                    file: "./cert/Carlos/diplomeDev.png",
                    desc: "Certifica la finalización de un curso completo en desarrollo web full-stack — incluyendo frontend (HTML, CSS, JavaScript, UI/UX) y backend (PHP, Python, bases de datos) — y en creación de aplicaciones móviles usando tecnología PWA (Progressive Web Apps).",
                    featured: true,
                },
                {
                    name: "Cisco CCNA 4: CyberOps Associate",
                    file: "./cert/Cisco/CCNA4.png",
                    desc: "Certifica la finalización exitosa del curso Cisco CyberOps Associate enfocado en operaciones de ciberseguridad y trabajo en un Security Operations Center (SOC). Se estudiaron monitoreo de redes, análisis de amenazas e incidentes, protocolos de red y métodos de detección de ataques. Se adquirieron habilidades en análisis forense digital, protección de endpoints, análisis de tráfico de red y uso de herramientas como Wireshark, SIEM y tecnologías de respuesta a incidentes.",
                    featured: true,
                },
                {
                    name: "Cisco CCNA 3: Enterprise Networking, Security and Automation",
                    file: "./cert/Cisco/CCNA3.png",
                    desc: "Certifica la finalización exitosa del tercer curso del programa de preparación para la certificación CCNA. Se estudiaron tecnologías de redes empresariales, enrutamiento OSPF, infraestructura WAN, fundamentos de seguridad de red y automatización. Se adquirieron habilidades en protección de dispositivos y tráfico de red, uso de ACL, VPN y SSH, así como conceptos modernos de SDN, virtualización y automatización de infraestructura de red.",
                    featured: true,
                },
                {
                    name: "Cisco CCNA 2: Conmutación, Enrutamiento y Fundamentos de Redes Inalámbricas",
                    file: "./cert/Cisco/CCNA2.png",
                    desc: "Certifica la finalización exitosa del segundo curso del programa de formación para la certificación CCNA. Se estudiaron las tecnologías clave de conmutación, enrutamiento y redes inalámbricas. Incluye la configuración y administración de VLAN, el enrutamiento inter-VLAN, los protocolos STP y EtherChannel, la configuración de routers y switches Cisco, así como los fundamentos del diseño y la seguridad de redes LAN y WLAN.",
                    featured: true,
                },
                {
                    name: "Cisco CCNA 1: Introducción a las Redes",
                    file: "./cert/Cisco/CCNA1.png",
                    desc: "Certifica la finalización exitosa del primero de tres cursos en la ruta hacia la certificación CCNA. Cubre los fundamentos de redes, incluyendo la arquitectura de red, el modelo OSI, direccionamiento IPv4/IPv6, enrutamiento, protocolos Ethernet y configuración básica de dispositivos con Cisco CLI.",
                },
                {
                    name: "Cisco IT Essentials: Hardware y Software de PC",
                    file: "./cert/Cisco/IT_Essentials.png",
                    desc: "Certifica la finalización exitosa del curso Cisco IT Essentials. Cubre fundamentos del hardware y software de PC y dispositivos móviles: componentes internos, ensamblaje del sistema, instalación de sistemas operativos y aplicaciones, mantenimiento y solución de problemas de hardware/software, impresoras y dispositivos móviles, redes básicas y seguridad, virtualización y computación en la nube.",
                },
                {
                    name: "IBM Data Visualization with Python",
                    file: "./cert/IBM/Data Visualization with Python.png",
                    desc: "Certifica la finalización exitosa del curso IBM Data Visualization with Python. Se estudiaron técnicas de visualización y análisis de datos utilizando Python y librerías como Matplotlib, Seaborn, Plotly y Folium. Se adquirieron habilidades en la creación de gráficos interactivos, dashboards, mapas, diagramas y reportes visuales, así como métodos de interpretación y presentación de datos para Data Science y analítica.",
                    featured: true,
                },
                {
                    name: "IBM Python 101 for Data Science",
                    file: "./cert/IBM/Python 101 for Data Science.png",
                    desc: "Certifica la finalización exitosa del curso IBM Python 101 for Data Science. Se estudiaron fundamentos de programación en Python, estructuras de datos, funciones, ciclos, manejo de archivos y programación orientada a objetos. Se adquirieron habilidades en el uso de Pandas y NumPy, trabajo en Jupyter Notebook, procesamiento y análisis de datos, así como métodos básicos de automatización y preparación de datos para Data Science.",
                    featured: true,
                },
                {
                    name: "UCI Inicio y Planificación de Proyectos",
                    file: "./cert/Coursera/Inicio y planificación de proyectos.png",
                    desc: "Certifica la finalización exitosa del curso UCI Inicio y Planificación de Proyectos de University of California, Irvine. Se estudiaron fundamentos de gestión de proyectos, planificación y definición de objetivos, gestión de stakeholders, administración del alcance y creación de estructuras Work Breakdown Structure (WBS). Se adquirieron habilidades en documentación de proyectos, evaluación de riesgos, estructuras organizacionales y colaboración efectiva dentro de equipos de proyecto.",
                },
                {
                    name: "Microsoft & UCI Project Management Fundamentals",
                    file: "./cert/Coursera/Project Management Fundamentals.png",
                    desc: "Certifica la finalización exitosa del curso Project Management Fundamentals de Microsoft. Se estudiaron principios fundamentales de gestión de proyectos, ciclo de vida del proyecto, planificación de tareas y recursos, gestión de riesgos, tiempos y presupuestos. Se adquirieron habilidades en colaboración de equipos, seguimiento de proyectos, documentación y uso de herramientas modernas de project management.",
                },
                {
                    name: "Certificado de Programador OOP",
                    file: "./cert/Carlos/programadorOOP.png",
                    desc: "Incluye los conceptos clave de la programación orientada a objetos (POO): encapsulamiento, herencia, polimorfismo y abstracción, con implementación práctica en lenguajes de alto nivel.",
                },
                {
                    name: "Certificado de Desarrollador Front-end",
                    file: "./cert/Carlos/devFrontEnd.png",
                    desc: "Otorgado tras completar un curso de desarrollo frontend enfocado en HTML5, CSS3, JavaScript, diseño responsivo, compatibilidad entre navegadores y principios de diseño UI/UX.",
                },
                {
                    name: "Certificado de Desarrollador Back-end",
                    file: "./cert/Carlos/devBackEnd.png",
                    desc: "Certifica conocimientos en desarrollo backend con PHP y Python, manejo de bases de datos, integración de APIs REST, arquitectura de aplicaciones web y seguridad.",
                },
                {
                    name: "Certificado de Desarrollador de Videojuegos",
                    file: "./cert/Carlos/devGame.png",
                    desc: "Incluye fundamentos del desarrollo de videojuegos: diseño, programación en Unity, así como nociones básicas de marketing y monetización en la industria del gaming.",
                },
                {
                    name: "Certificado de Desarrollador Móvil",
                    file: "./cert/Carlos/devPhone.png",
                    desc: "Certifica habilidades en desarrollo móvil usando tecnología PWA — creación de apps multiplataforma con acceso offline, instalación y funciones integradas del dispositivo.",
                },
            ],

            degree: "Título universitario",
            degree_text: "Obtuve una Licenciatura en Ingeniería en Software y Redes en la Universidad del Valle de México (UVM), donde recibí formación teórica y práctica en desarrollo de software moderno, ingeniería de sistemas e infraestructura de TI.\n\nDurante mis estudios combiné la formación académica con experiencia freelance y profesional en la industria, lo que me permitió aplicar conocimientos técnicos en entornos reales y desarrollar un perfil de ingeniería práctico y completo.\n\nActualmente curso una Maestría en Ingeniería con especialización en Inteligencia Artificial en UVM. El programa se enfoca en machine learning, sistemas inteligentes, soluciones basadas en datos y prácticas modernas de ingeniería de software. Estoy desarrollando habilidades técnicas avanzadas y aplicando métodos de IA a problemas reales.",
            degree_tags_title: "Áreas clave de estudio",
            degree_tags: ["C", "C++", "C#", "Java", "Python", "SQL", "Bases de datos relacionales", "Android", "Desarrollo móvil", "Infraestructura de redes", "Sistemas operativos", "Automatización", "Arquitectura de computadoras", "Ingeniería de software", "Análisis de sistemas", "Modelado", "Ciberseguridad", "Protocolos de comunicación de datos"],
            education_programs: [
                {
                    id: "uvm-bachelor",
                    label: "Licenciatura UVM",
                    school: "Universidad del Valle de México",
                    title: "Licenciatura, Ingeniería en Diseño de Redes y Software",
                    period: "Mayo 2023 - mayo 2026",
                    status: "Completada",
                    gradeLabel: "Promedio",
                    grade: "9.71",
                    start: "2023-05",
                    end: "2026-05",
                    celebration: "Universidad completada. Ingeniería en Diseño de Software y Redes desbloqueada.",
                    documents: [
                        {
                            name: "Constancia de egreso de la licenciatura",
                            file: "./cert/uvm/diploma.png",
                            desc: "Constancia de Egreso expedida por la Universidad del Valle de México (UVM) el 5 de agosto de 2026. Confirma que concluí satisfactoriamente la Licenciatura en Ingeniería en Diseño de Software y Redes.",
                        },
                        {
                            name: "Certificado del examen final EGEL",
                            file: "./cert/uvm/Egel.png",
                            desc: "Confirma la realización del examen final EGEL en la Universidad del Valle de México (UVM) y sirve como documento adicional de respaldo de mis estudios de licenciatura completados.",
                        },
                    ],
                },
                {
                    id: "masters-current",
                    label: "Maestría UVM",
                    school: "Universidad del Valle de México",
                    title: "Maestría en Ingeniería con especialización en Inteligencia Artificial",
                    period: "Junio 2026 - julio 2028",
                    status: "En curso",
                    start: "2026-06",
                    end: "2028-07",
                    celebration: "Maestría en Inteligencia Artificial en curso. El siguiente capítulo académico está activo.",
                    documents: [],
                },
            ],
        },

        ru: {
            title: "Full Stack инженер",
            hero_focus: "Backend · Desktop-разработка · Интеграции",
            work_mode: "Удалённо",
            location: "Нахожусь в Мексике",
            availability: "Открыт к предложениям",
            cta_projects: "Посмотреть проекты",
            cta_contact: "Связаться со мной",
            intro: "Я — Егор Павлов, Full Stack инженер. Разрабатываю веб- и desktop-приложения, backend-системы, CRM-интеграции и инструменты автоматизации. Работаю с проектами полного цикла — от архитектуры и бизнес-логики до интерфейса, Docker-инфраструктуры и развёртывания.",
            skills: "Ключевые навыки",
            skills_list: ["Фуллстек-разработка (frontend + backend)", "Языки: C++, C#, Python, Java, JavaScript, PHP", "Фреймворки и библиотеки: Django, Vue.js, Node.js, Qt, .NET", "Десктоп-приложения (Qt, WinForms, JavaFX, .NET)", "DevOps: Linux, Git, Docker, CI/CD, автоматизация процессов", "Интеграции с CRM (Bitrix24, amoCRM), API, вебхуки", "Базы данных: PostgreSQL, MySQL, SQLite, MongoDB", "Работа с REST API, JSON, XML, WebSocket"],
            skill_groups: [
                { title: "Backend", icon: "fas fa-server", items: ["Python", "Django", "Node.js", "PHP", "REST API", "WebSocket"] },
                { title: "Frontend и Full Stack", icon: "fas fa-code", items: ["JavaScript", "Vue.js", "HTML/CSS", "Bootstrap", "jQuery"] },
                { title: "Desktop и системная разработка", icon: "fas fa-desktop", items: ["C++", "C#", "Java", "Qt", ".NET", "WinForms", "JavaFX"] },
                { title: "DevOps и интеграции", icon: "fas fa-gears", items: ["Docker", "Linux", "CI/CD", "Битрикс24", "amoCRM", "PostgreSQL", "MySQL"] },
            ],
            projects: "Проекты",
            projects_commercial: "Коммерческие проекты",
            projects_pet: "Pet-проекты",
            project_role_label: "Роль: ",
            project_result_label: "Результат: ",
            image_loading: "Загрузка изображения...",
            nav_label: "Навигация по портфолио",
            nav_prompt: "Маршрут",
            nav_overview: "Обо мне",
            nav_skills: "Навыки",
            nav_projects: "Проекты",
            nav_education: "Образование",
            nav_certificates: "Сертификаты",
            nav_contact: "Контакты",
            nav_start: "Начать знакомство",
            certs_show_all: "Показать все сертификаты",
            certs_show_less: "Свернуть сертификаты",
            certs_key: "Ключевые сертификаты",
            certs_additional: "Дополнительные сертификаты",
            degree_summary: "Выпускник бакалавриата UVM по инженерии проектирования программного обеспечения и сетей. Сейчас учусь в магистратуре по инженерии со специализацией в искусственном интеллекте.",
            education_more: "Подробнее об образовании",
            education_less: "Скрыть подробности",
            project_list: [
                {
                    name: "Платформа интеграции онлайн-бронирования и СКУД",
                    type: "commercial",
                    areas: ["Разработка продукта", "CRM-интеграция", "Контроль доступа", "Платежи", "Инфраструктура"],
                    role: "Ведущий разработчик: backend, frontend, Docker-деплой, CRM и интеграция со СКУД.",
                    impact: "Объединил бронирование, оплату, синхронизацию с Битрикс24 и управление доступом в единую систему.",
                    stack: ["Django", "Docker", "Битрикс24", "PHP", "WebSocket"],
                    file: ["./projects/24reson/1.png", "./projects/24reson/2.png", "./projects/24reson/3.png"],
                    desc: "Коммерческий проект для компании, совмещающий онлайн-бронирование переговорных комнат и тарифов с интеграцией в систему контроля доступа (СКУД) и CRM Битрикс24. Реализовал backend на Django с использованием Docker, обеспечив удобный деплой и управление окружением. Система включает регистрацию пользователей, личный кабинет, календарь бронирований и синхронизацию данных с Битрикс24. Настроил автоматическое создание карточек клиентов, сделок и товаров в CRM, а также управление доступом к помещениям через СКУД. Разработал сервер СКУД на чистом PHP с обменом командами по WebSocket и логированием всех событий доступа. Система поддерживает двустороннюю синхронизацию, обработку платежей и динамическое управление филиалами, тарифами и комнатами. Руководил командой из 3 человек, выполняя основную часть backend и frontend-разработки.",
                    sections: [
                        {
                            title: "Что это",
                            text: "Коммерческая система для бронирования переговорных комнат, управления тарифами, оплатами, CRM-данными и физическим доступом в помещения. Задача была в том, чтобы онлайн-бронирование, Битрикс24 и СКУД работали вместе, а не как несколько отдельных процессов.",
                        },
                        {
                            title: "Что я сделал",
                            text: "Я разработал большую часть продукта end-to-end: backend на Django, frontend-сценарии, Docker-деплой, авторизацию, личные кабинеты, календарь бронирований и инструменты для управления филиалами, тарифами и комнатами. Настроил синхронизацию с Битрикс24 и автоматическое создание клиентов, сделок, товаров и данных, связанных с бронированиями. Также связал оплаты и роли пользователей с правами физического доступа, а отдельно написал сервис СКУД на чистом PHP с командами через WebSocket и логами событий доступа в реальном времени.",
                        },
                        {
                            title: "Эффект",
                            text: "Система убрала много ручной координации между бронированиями, CRM, оплатами и доступом в комнаты. Теперь филиалы, тарифы, комнаты, пользователи, события прохода и CRM-данные можно вести из одного рабочего процесса, а платформа сама держит синхронизацию между бронированием, Битрикс24, оплатами и сервисом доступа.",
                        },
                    ],
                },
                {
                    name: "PWA-приложение для уведомлений клиентов и юридической поддержки",
                    type: "commercial",
                    areas: ["Клиентский портал", "Backend API", "CRM-интеграция", "Уведомления"],
                    role: "Ответственный за backend: архитектура API, Docker, интеграция с Битрикс24 и Telegram-ботом.",
                    impact: "Собрал личный кабинет для клиентов с долгами, оплатой, уведомлениями и связью с юристами.",
                    stack: ["Flask", "Docker", "Vue", "Битрикс24", "Telegram API"],
                    file: ["./projects/pwa_site/1.png"],
                    desc: "Коммерческий проект в формате Progressive Web App для взаимодействия клиентов с юридическим отделом компании. Реализовал API-сервер на Flask (Python) с использованием Docker как центральное звено для интеграции приложения с CRM Битрикс24 и Telegram-ботом. Клиенты через личный кабинет могут просматривать свои задолженности, получать уведомления, оплачивать услуги и связываться с юристами напрямую. Для каждого клиента в системе ведётся индивидуальный кейс с отслеживанием статуса. Frontend разработан на Vue.js (Vite), интеграцию с backend и бизнес-логику выполнил лично. Работал в команде из 3 человек, отвечая за всю серверную часть, Docker-настройку и стыковку backend с версткой, выполненной другими разработчиками.",
                    sections: [
                        {
                            title: "Что это",
                            text: "Коммерческое PWA-приложение для связи клиентов с юридическим отделом. Через личный кабинет клиент может следить за своим делом, видеть информацию по оплатам, получать уведомления и напрямую связываться с юристами.",
                        },
                        {
                            title: "Что я сделал",
                            text: "Я спроектировал и реализовал backend на Flask: REST API, бизнес-логику, обмен данными между сервисами, интеграцию с CRM Битрикс24 и Telegram-ботом для уведомлений. Упаковал backend в Docker и подключил его к frontend на Vue.js (Vite), который делала команда. На моей стороне были API для экранов, статусы кейсов, данные по оплатам, уведомления и сценарии коммуникации с клиентами. Работал в команде из 3 человек и отвечал за backend-архитектуру, API-дизайн, Docker-настройку и деплой.",
                        },
                        {
                            title: "Эффект",
                            text: "Клиентам стало проще понимать, что происходит с их делом: статус, обновления, оплаты и связь с юристами находятся в одном кабинете. Для внутренней команды это уменьшило ручные обновления и объединило CRM, уведомления и отслеживание кейсов в один рабочий процесс.",
                        },
                    ],
                },
                {
                    name: "Сюжетный Minecraft-мод с уникальной игровой механикой",
                    type: "pet",
                    areas: ["Игровые системы", "Логика NPC", "Сюжет", "Событийные механики"],
                    role: "Gameplay-разработчик: события, логика NPC, боссы, триггеры и прогрессия.",
                    impact: "Превратил сервер в сюжетное приключение с динамической музыкой, союзниками, врагами и концовками.",
                    stack: ["Java", "Spigot", "Game Logic", "Events"],
                    file: ["./projects/strangers_in_rosaville/1.png", "./projects/strangers_in_rosaville/2.png", "./projects/strangers_in_rosaville/3.png", "./projects/strangers_in_rosaville/4.png"],
                    desc: "Проект на Java Spigot для серверов Minecraft, превращающий игру в полноценное приключение с сюжетом, секретами и динамическими событиями. Разработал систему фоновой музыки, которая меняется в зависимости от локации и триггеров на карте. Созданы дружественные NPC, которые могут вести диалог, следовать за игроком и помогать в прохождении, а также вражеские NPC с уникальной личностью и возможностью сюжетных поворотов (враг может стать союзником). Реализованы босс-файты, несколько концовок и интерактивные механики, включая кастомные инструменты и скины. Работа велась командой из 2 человек: я полностью отвечал за программирование и код, другой разработчик занимался скинами, дизайном и историей, при этом я также участвовал в создании контента и сюжета. Проект демонстрирует навыки разработки сложных игровых систем, управление событиями и интеграцию различных игровых механик.",
                    sections: [
                        {
                            title: "Что это",
                            text: "Пет-проект на Java Spigot для Minecraft-сервера. Мы хотели сделать сервер похожим на небольшое приключение: с сюжетом, секретами, динамическими событиями, прогрессией и кастомными взаимодействиями.",
                        },
                        {
                            title: "Что я собрал",
                            text: "В команде из 2 человек я отвечал за код и gameplay-логику. Сделал адаптивную музыку по локациям и триггерам, дружественных NPC с диалогами и поведением спутников, врагов с характером и возможными изменениями отношений, босс-файты, несколько концовок, кастомные инструменты, скины и события в мире. Ещё участвовал в идеях для контента и сюжета, пока второй участник больше занимался скинами, дизайном и историей.",
                        },
                        {
                            title: "Что показывает",
                            text: "Проект был весёлый, но технически не пустой. Я получил практику с event-driven gameplay, логикой NPC, trigger-системами, ветвящимися исходами и интерактивными механиками на Java, а обычный сервер стал ближе к небольшому сюжетному приключению.",
                        },
                    ],
                },

                {
                    name: "Личное облачное хранилище (аналог Google Drive)",
                    type: "pet",
                    areas: ["Full Stack продукт", "Работа с файлами", "Квоты пользователей", "Админ-инструменты"],
                    role: "Solo-разработчик: продуктовая логика, backend, frontend, админка и Docker-окружение.",
                    impact: "Собрал рабочее приватное облако с квотами хранилища и полным управлением файлами.",
                    stack: ["Django", "Docker", "Bootstrap", "jQuery"],
                    file: ["./projects/fileExchange/1.png", "./projects/fileExchange/2.png", "./projects/fileExchange/3.png"],
                    desc: "Пет-проект на Django с Docker, Bootstrap и jQuery, представляющий собой личное облачное хранилище файлов с функционалом, аналогичным Google Drive. Реализовал контроль выделяемой памяти для пользователей, отображение оставшегося пространства в удобном и наглядном интерфейсе, а также возможности управления файлами: перемещение, копирование, переименование, удаление и просмотр информации о файлах. Предусмотрена система администрирования для управления пользователями и хранилищем. Проект демонстрирует навыки разработки сложных веб-приложений, работу с серверной логикой, интеграцию интерфейса с backend и организацию хранения и обработки больших объёмов данных. Выполнен полностью мной, включая настройку Docker и разработку фронтенда и бэкенда.",
                    sections: [
                        {
                            title: "Что это",
                            text: "Пет-проект личного облачного хранилища, по идее похожий на небольшой Google Drive. Я делал его, чтобы отработать лимиты памяти для пользователей, файловые сценарии и администрирование.",
                        },
                        {
                            title: "Что я собрал",
                            text: "Полностью собрал приложение на Django, Docker, Bootstrap и jQuery. Реализовал квоты памяти для пользователей, отображение оставшегося пространства, админ-инструменты для управления пользователями и хранилищем, а также файловые операции: перемещение, копирование, переименование, удаление и просмотр деталей. Делал и backend, и frontend: серверную логику, интеграцию интерфейса и Docker-настройку.",
                        },
                        {
                            title: "Что показывает",
                            text: "Это практичный fullstack-проект: пользователи, квоты, файловые сценарии, админка, frontend-backend интеграция и работа с файловыми данными. Не просто статичная страница, а приложение с нормальной продуктовой логикой.",
                        },
                    ],
                },
            ],
            certs: "Сертификаты",
            certs_list: [
                {
                    name: "Диплом разработчика веб-сайтов и мобильных приложений",
                    file: "./cert/Carlos/diplomeDev.png",
                    desc: "Подтверждает успешное прохождение курса по созданию веб-сайтов с применением технологий как фронтенд (HTML, CSS, JavaScript, UI/UX), так и бэкенд (PHP, Python, базы данных), а также разработке мобильных приложений с использованием PWA (Progressive Web Apps).",
                    featured: true,
                },
                {
                    name: "Cisco CCNA 4: CyberOps Associate",
                    file: "./cert/Cisco/CCNA4.png",
                    desc: "Подтверждает успешное завершение курса Cisco CyberOps Associate, посвящённого операциям кибербезопасности и работе Security Operations Center (SOC). Изучены мониторинг сетей, анализ угроз и инцидентов, сетевые протоколы и методы обнаружения атак. Освоены основы цифровой криминалистики, защиты конечных устройств, анализа сетевого трафика, а также использование инструментов Wireshark, SIEM и технологий реагирования на инциденты.",
                    featured: true,
                },
                {
                    name: "Cisco CCNA 3: Enterprise Networking, Security and Automation",
                    file: "./cert/Cisco/CCNA3.png",
                    desc: "Подтверждает успешное завершение третьего курса программы подготовки к сертификации CCNA. Изучены технологии корпоративных сетей, маршрутизация OSPF, WAN-инфраструктура, основы сетевой безопасности и автоматизации. Освоены методы защиты сетевых устройств и трафика, работа с ACL, VPN и SSH, а также современные подходы к SDN, виртуализации и автоматизации сетевой инфраструктуры.",
                    featured: true,
                },
                {
                    name: "Cisco CCNA 2: Коммутация, маршрутизация и основы беспроводных сетей",
                    file: "./cert/Cisco/CCNA2.png",
                    desc: "Подтверждает успешное завершение второго курса программы подготовки к сертификации CCNA. Изучены ключевые технологии коммутации, маршрутизации и беспроводных сетей. Освоены конфигурация и управление VLAN, межвлановая маршрутизация, протоколы STP и EtherChannel, настройка маршрутизаторов и коммутаторов Cisco, а также основы проектирования и защиты локальных сетей и WLAN.",
                    featured: true,
                },
                {
                    name: "Cisco CCNA 1: Введение в сети",
                    file: "./cert/Cisco/CCNA1.png",
                    desc: "Подтверждает успешное завершение первого из трёх курсов программы подготовки к сертификации CCNA. Освоены основы сетевых технологий, включая архитектуру сетей, модель OSI, адресацию IPv4/IPv6, маршрутизацию, протоколы Ethernet и настройку сетевых устройств с использованием Cisco CLI.",
                },
                {
                    name: "Cisco IT Essentials: Аппаратное и программное обеспечение ПК",
                    file: "./cert/Cisco/IT_Essentials.png", // замени путь, если нужно
                    desc: "Подтверждает успешное завершение курса Cisco IT Essentials. Освоены основы работы ПК и мобильных устройств: понимание внутренней архитектуры, сборка, установка ОС и приложений, профилактика и устранение неисправностей аппаратной и программной части, принтеров, мобильных устройств, базовые сетевые и меры безопасности, а также основы виртуализации и облачных технологий.",
                },
                {
                    name: "IBM Data Visualization with Python",
                    file: "./cert/IBM/Data Visualization with Python.png",
                    desc: "Подтверждает успешное завершение курса IBM Data Visualization with Python. Изучены методы визуализации и анализа данных с использованием Python и библиотек Matplotlib, Seaborn, Plotly и Folium. Освоено создание интерактивных графиков, дашбордов, карт, диаграмм и визуальных отчётов, а также методы представления и интерпретации данных для Data Science и аналитики.",
                    featured: true,
                },
                {
                    name: "IBM Python 101 for Data Science",
                    file: "./cert/IBM/Python 101 for Data Science.png",
                    desc: "Подтверждает успешное завершение курса IBM Python 101 for Data Science. Изучены основы программирования на Python, структуры данных, функции, циклы, работа с файлами и объектно-ориентированное программирование. Освоены библиотеки Pandas и NumPy, работа в Jupyter Notebook, обработка и анализ данных, а также базовые методы автоматизации и подготовки данных для Data Science.",
                    featured: true,
                },
                {
                    name: "UCI Project Initiation and Planning",
                    file: "./cert/Coursera/Inicio y planificación de proyectos.png",
                    desc: "Подтверждает успешное завершение курса UCI Project Initiation and Planning от University of California, Irvine. Изучены основы управления проектами, планирование и определение целей проекта, работа со stakeholder’ами, управление scope и построение Work Breakdown Structure (WBS). Освоены методы проектной документации, оценки рисков, организационных структур и эффективного взаимодействия внутри проектной команды.",
                },
                {
                    name: "Microsoft & UCI Project Management Fundamentals",
                    file: "./cert/Coursera/Project Management Fundamentals.png",
                    desc: "Подтверждает успешное завершение курса Project Management Fundamentals от Microsoft. Изучены ключевые принципы управления проектами, жизненный цикл проекта, планирование задач и ресурсов, управление рисками, сроками и бюджетом. Освоены методы командного взаимодействия, контроля выполнения проектов, работы с документацией и использования современных инструментов project management.",
                },
                {
                    name: "Программист ООП",
                    file: "./cert/Carlos/programadorOOP.png",
                    desc: "Сертификат, подтверждающий знания и практические навыки объектно-ориентированного программирования (ООП), включая принципы инкапсуляции, наследования, полиморфизма и абстракции, с применением на языках программирования высокого уровня.",
                },
                {
                    name: "Front-end разработчик",
                    file: "./cert/Carlos/devFrontEnd.png",
                    desc: "Сертификат по фронтенд-разработке. Включает углублённое изучение HTML5, CSS3, JavaScript, принципов адаптивной и кроссбраузерной вёрстки, а также основ UI/UX-дизайна и взаимодействия с пользователем.",
                },
                {
                    name: "Back-end разработчик",
                    file: "./cert/Carlos/devBackEnd.png",
                    desc: "Подтверждает освоение основ серверной разработки с использованием PHP и Python, взаимодействия с базами данных, REST API, а также принципов безопасности и архитектуры веб-приложений.",
                },
                {
                    name: "Разработчик игр",
                    file: "./cert/Carlos/devGame.png",
                    desc: "Сертификат по основам геймдева. Изучены принципы проектирования и программирования видеоигр, основы работы с игровыми движками (Unity), а также вводный курс по маркетингу и монетизации игр.",
                },
                {
                    name: "Мобильный разработчик",
                    file: "./cert/Carlos/devPhone.png",
                    desc: "Сертификат, подтверждающий знания в области мобильной разработки на основе PWA — создание кроссплатформенных приложений с оффлайн-доступом, установкой на устройства и интеграцией с функциями смартфона.",
                },
            ],
            degree: "Диплом",
            degree_text: "Я получил степень бакалавра в области инженерии программного обеспечения и сетей в Universidad del Valle de México (UVM), где прошёл теоретическую и практическую подготовку в современной разработке ПО, системной инженерии и IT-инфраструктуре.\n\nВо время учёбы я совмещал академическую подготовку с freelance- и профессиональным опытом в индустрии. Это позволило применять технические знания в реальных проектах и сформировать практичный, разносторонний инженерный подход.\n\nСейчас я учусь в магистратуре по инженерии со специализацией в искусственном интеллекте в UVM. Программа сфокусирована на machine learning, интеллектуальных системах, data-driven решениях и современных практиках software engineering. Я развиваю продвинутые технические навыки и применяю методы ИИ к реальным задачам.",
            degree_tags_title: "Ключевые направления обучения",
            degree_tags: ["C", "C++", "C#", "Java", "Python", "SQL", "Реляционные базы данных", "Android", "Мобильная разработка", "Сетевая инфраструктура", "Операционные системы", "Автоматизация", "Архитектура компьютеров", "Программная инженерия", "Системный анализ", "Моделирование", "Кибербезопасность", "Протоколы передачи данных"],
            education_programs: [
                {
                    id: "uvm-bachelor",
                    label: "Бакалавриат UVM",
                    school: "Universidad del Valle de México",
                    title: "Бакалавриат, Ingeniero en Diseño de Redes y Software",
                    period: "Май 2023 - май 2026",
                    status: "Завершено",
                    gradeLabel: "Средний балл",
                    grade: "9.71",
                    start: "2023-05",
                    end: "2026-05",
                    celebration: "Университет закончен. Инженерия ПО и сетей разблокирована.",
                    documents: [
                        {
                            name: "Подтверждение окончания бакалавриата",
                            file: "./cert/uvm/diploma.png",
                            desc: "Документ об окончании обучения, выданный Universidad del Valle de México (UVM) 5 августа 2026 года. Подтверждает, что я успешно завершил бакалаврскую программу по инженерии проектирования программного обеспечения и сетей (Licenciatura en Ingeniería en Diseño de Software y Redes).",
                        },
                        {
                            name: "Сертификат финального экзамена EGEL",
                            file: "./cert/uvm/Egel.png",
                            desc: "Подтверждает сдачу финального экзамена EGEL в Universidad del Valle de México (UVM) и служит дополнительным подтверждением завершённого бакалавриата.",
                        },
                    ],
                },
                {
                    id: "masters-current",
                    label: "Магистратура UVM",
                    school: "Universidad del Valle de México",
                    title: "Магистратура по инженерии со специализацией в искусственном интеллекте",
                    period: "Июнь 2026 - июль 2028",
                    status: "В процессе",
                    start: "2026-06",
                    end: "2028-07",
                    celebration: "Магистратура по искусственному интеллекту в процессе. Следующая академическая глава запущена.",
                    documents: [],
                },
            ],
        },
    },
};
